### ISSUE TITLE
1.16 Forge Moving Elevators visual issue

### ISSUE THREAD

**Issue by George-Irinel-Necula** [tr7zw/EntityCulling#62]
So basically the block interface disapears when i leave the area and come back tried to unistall some performance mods and came to conclusion that it might be the entity culling mod .It might be a entity culling mod bug but im not sure im using Forge 1.16.5 36.2.28 and both mods latest version.
![Screenshot_4](https://user-images.githubusercontent.com/69117236/154824672-f92f0873-43a9-46b6-97bd-9fc4eaec25ee.png)
![Screenshot_3](https://user-images.githubusercontent.com/69117236/154824668-b66e7f42-c45f-4974-ac1f-0fafa336a91a.png)

Have a good day!

**Comment by tr7zw** [comment]
Huh, is this forge or fabric? If it's forge the mod author of Moving Elevators should fix the visual bounding box of the block, and as a hotfix you can add the block to the whitelist in the config file.

**Comment by George-Irinel-Necula** [comment]
Hello! Its the forge version the latest for both mods for 1.16.5. Have a great day!

**Comment by tr7zw** [comment]
Huh then it's probably more of a logical issue with that mod. Like I said, use F3 to get the block name, and then you can add it in the config file in the config folder to the block whitelist.

**Comment by George-Irinel-Necula** [comment]
Update:Adding blocks to whitelist in config doesnt work its still doesnt render when i come back the only thing that works is removing the entity culling mod . Thanks for the help!

**Comment by tr7zw** [comment]
Did you restart the game after adding the block? The config will only load once when the game loads. I'll look at it later.

**Comment by George-Irinel-Necula** [comment]
Yes , i restarted my game multiple times no result and checked if i wrote the config corectly.

**Comment by tr7zw** [comment]
I'll close this for now as it doesn't seem to be a widespread issue. Newer versions of the mod will handle this better(assuming that the elevator mod has setup the flags correctly).
